# Generated by Django 4.1.6 on 2023-02-28 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_remove_task_date_task_custom_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата и время удаления'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='удалено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='custom_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 28, 4, 50, 45, 553216, tzinfo=datetime.timezone.utc), verbose_name='custom_date'),
        ),
    ]
